name: Convert PDF to Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install ghostscripts
        run: sudo apt-get install -y ghostscript
      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick
      - name: Allow PDF read
        run: sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
      - name: log
        run: ls -l
      - name: Convert PDF to Image
        run: convert -density 300 Maryll_Castelino_Resume.pdf -quality 100 -background white -alpha remove resume.png
      - name: Commit image file to repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update resume image file"
          add: "resume.png"
